### PR TITLE
Request to test our model trained with private data.

### PR DESCRIPTION
**Pull request by iou2much**
Hello. Jiayu. We request to test our model trained with our business data. 

As there's no public API yet, we encrypt the model and upload to the OSS. And it could only be used with the asr binary package, which you can find in Dockerfile.

### CODE REVIEW

**Comment by iou2much** [comment]
BTW, sorry for that I accidentally push a coredump file to the OSS. As I thought it only uploads assets folder, and forgot to clean up first.
Please delete the core.* file in OSS to avoid costing extra fees.

**Comment by dophist** [comment]
There seems to be some permission problems when i was reproducing your model-image:
1). scripts in assets/ don't have execution permission, and top level scripts call them in a ./xxx style, I fixed this manually by chmod +x assets/xxx
2). after fixing 1), log.SBI gives:
/sbin/ldconfig.real: Can't link /opt/libtorch/lib/libgomp.so.1 to libgomp-52f2fd74.so.1
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied

I haven't got time to look into your docker env for more details, maybe you can validate first on MINI or ZH00000(or possibly other unlocked sets), to see any of these happens.

**Comment by iou2much** [comment]
Thank you for looking into this PR.
Actually I tested the whole procedures on my server , and I haven't seen any of these errors.

I think the 2nd issue might be related to the user permission, as I use `root` user on my server, and you might be using normal user ?
Never mind. I change the SBI. it no long asks for super permission now. Please try again. Thanks

**Comment by iou2much** [comment]
And please pull the model again, thank you.

**Comment by iou2much** [comment]
And please pull the model again, thank you.

**Comment by dophist** [comment]
Cool, now it runs smoothly. Merging.

**Pull request merged**
