### PR TITLE
Support Microsoft batch API

### PR DESCRIPTION
**Pull request by liankuai**
It can support Microsoft batch API. We need to set 4 parameters, they are SUBSCRIPTION_KEY, CONNECTION_STRING, STORAGE_ACCOUNT, STORAGE_KEY in the root directory of the 'microsoft_batch_zh' model. You can get help from below links.

SUBSCRIPTION_KEY:  Speech service key for ASR.
CONNECTION_STRING: Connection string for blob storage.
STORAGE_ACCOUNT: Account name for blob storage.
STORAGE_KEY: Key for blob storage.

Batch API
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/batch-transcription

Blob storage
https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal

### CODE REVIEW

**Comment by dophist** [comment]
@liankuai  I see a lot of unnecessary files included in this PR, the model image should contain essential resources for ASR inference, docs and test cases should not be part of it. Instead, you can put official links to these materials in comments or in a standalone markdown, so that anyone can easily dive into more details following these directives.

**Comment by liankuai** [comment]
> @liankuai I see a lot of unnecessary files included in this PR, the model image should contain essential resources for ASR inference, docs and test cases should not be part of it. Instead, you can put official links to these materials in comments or in a standalone markdown, so that anyone can easily dive into more details following these directives.

@dophist  I have removed irrelevant code. Could you please review it?

**Comment by dophist** [comment]
I still have concerns about this PR:

Do endpoint users really need to write 4000 lines of code like this PR, to get access to ordinary Microsofts offline ASR?because that's really intimidating for other leaderboard users. Shouldn't most of these code be packaged into a Microsoft official repo and can be installed via a single pip command?

I don't want to be picky, but before merging this, I need to understand the reason why we *have to* dump the complexity of these 4000 lines of python code into *this repo*, that still seems unmaintainable and likely to be broken in the future.

**Comment by liankuai** [comment]
@dophist  I have improved the code to support restful batch API. Thanks very much.

**Pull request merged**
